### ISSUE TITLE
Generator cannot handle referenced types (in separate files)

### ISSUE THREAD

**Issue by oskarcarlstedt** [asyncapi/generator#1002]
#### Describe the bug
It looks like the generator cannot handle  types that are referenced in other files. Declaring the type locally in the schemas section works perfectly, but not when declaring the type in a separate file and referencing it.

I like to use the same model definitions in OpenAPI and AsyncAPI implementations. Therefore I want to share some types between these two types of API definitions.

#### How to Reproduce
Just run the generator  using the java-spring template and we gen an error saying this is not an AsynAPI file.

asyncapi: "2.6.0"
info:
  title: An asynchronous API
  version: 1.0.0
  description: |
    An API dealing with asynchronous actions on some objects

defaultContentType: application/json
channels:
  objects.new:
    subscribe:
      operationId: pushNewObjectToSubscribers
      message:
        $ref: "#/components/messages/ObjectMessage"

components:
  messages:
    ObjectMessage:
      payload:
        $ref: "types.yaml#/components/schemas/SomeType".  <<<--- This is the type that cannot be found

#### Expected behavior
Find and read the type in the reference file.

**Comment by derberg** [comment]
@oskarcarlstedt please format your example asyncapi file so it is easy to copy and paste so we can try replicating the issue. And share `types.yaml` too 🙏🏼

**Comment by michael-ball-ctct** [comment]
Hi @derberg 
Obviously, not quite the same example, but I'm fairly sure I'm running into the same issue with the following files in the same folder:
```yml
# asyncapi.yml
asyncapi: '2.6.0'
info:
  title: Account Service 2
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
    SignUpFailed:
      payload:
        $ref: ./asyncapi-ref.yml#/components/messages/SignUpFailure
```

```yml
# asyncapi-ref.yml
components:
  messages:
    SignUpFailure:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
          failure_reason:
            type: string
            description: The reason this signup was unsuccessful
```

Which results in:
![AsyncAPIRefFailure](https://github.com/asyncapi/generator/assets/139728307/6df27fde-e3f0-4022-97ff-947db7a77345)

Desired result would be that is contains the information contained in the `asyncapi-ref.yml` for the `SignUpFailure` message component, rather than just `Any`.


Hopefully this formatting and screenshot of the result helps to make this issue more clearly understandable - it's a significant thorn in my side. Cheers!
