### ISSUE TITLE
Blank page when generating html doc

### ISSUE THREAD

**Issue by mamyn0va** [asyncapi/generator#1063]
#### Describe the bug
When I generate the html doc from my asyncapi file, and I open it in my browser, I get a blank page (nothing displayed).

#### How to Reproduce

I use asyncapi/cli version 0.60.0.

`asyncapi generate fromTemplate asyncapi.yml --force-write @asyncapi/html-template -o public/asyncapi`

asyncapi.yml

```yaml
asyncapi: 2.5.0
info:
  title: Example
  version: 0.1.0
channels:
  user/signedup:
    subscribe:
      message:
        description: An event describing that a user just signed up.
        payload:
          type: object
          additionalProperties: false
          properties:
            fullName:
              type: string
            email:
              type: string
              format: email
            age:
              type: integer
              minimum: 18
```

#### Expected behavior
A nice asyncapi documentation.
