### ISSUE TITLE
How to get parameter name?

### ISSUE THREAD

**Issue by jdall** [asyncapi/generator#114]
Having the following spec:
```
channels
  test/eurisco/playground/0/1/status/{param1}/{param2}:
    parameters:
      - name: param1
        description: Parameter 1
        schema:
          type: string
      - name: param2
        description: Parameter 2
        schema:
          type: string
```
I have to get the parameter names in a non-typical way. 

In my template, I have
```
{%- for channelName, channel in asyncapi.channels() -%}
  {{channelName|log}}
  {%- for paramName, param in channel.parameters() %}
    {{param|log}}
    {{paramName|log}}
    {{param.name|log}}
    {{param._json.name|log}}
  {%- endfor %}
{%- endfor %}
```
which results in the following output
```
test/eurisco/playground/0/1/status/{param1}/{param2}
ChannelParameter {
  _json: 
   { name: 'param1',
     description: 'Parameter 1',
     schema: { type: 'string' } } }
0
undefined
param1
ChannelParameter {
  _json: 
   { name: 'param2',
     description: 'Parameter 2',
     schema: { type: 'string' } } }
1
undefined
param2
```
Why can't I get the parameter name the same way I get a channel name (via the 'for' loop)?
And why is the name not available as {{parameter.name}} ?

Running v0.13.1
