### ISSUE TITLE
Take websocket templates development to another level by adding more real-life fixtures

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#1418]
Create real production-ready AsyncAPI documents for existing public Websocket APIs so we can use them (like we use now, public echo services from postman and hoppscotch).

Scope doesn't define what exactly should be selected, can be Slack API, can be some crypto like Kraken or Gemini or some other exchange, or something else (open for proposals)

More important is to have a public API that anyone can subscribe to use for free for testing. 

Main scope/goal:
- have 2 AsyncAPI documents
- adjust existing JS and PY websocket template to support it
  - This means for sure replacement of the existing hardcoded single send message with as many as defined in AsyncAPI document
  - Enable authorization support - whatever is needed for given API
  - Might be that given API will require also enablement of generation of code basing on variables/queryparams

Possible change of scope: **super hard to predict amount of work. It really depends on the APIs that need to be supported, how complex they are. Might be that multiple PRs will be needed. This means that over weeks might be that scope will change to complete at least 1 document and modify at least one template**

**Comment by derberg** [comment]
I'll be working on that

**Comment by mattzinstagib** [comment]
### 🔥 AI-Generated Solution:

```
To properly tackle the GitHub bounty titled "Take websocket templates development to another level by adding more real-life fixtures", we need to design and implement a WebSocket-based template that is augmented with practical, real-life data scenarios. We'll create an example template using WebSockets, integrating it with AsyncAPI for documentation and design purposes.

### Solution Steps:

1. **WebSocket Template Development**
2. **Adding Real-Life Fixtures to Template**
3. **Utilizing AsyncAPI for Structuring the WebSocket Communication**
4. **Testing and Documentation**

### Step 1: WebSocket Template Development

Firstly, we need to build a basic template for a WebSocket communication. This template should be scalable, reusable, and adaptable for different real-life scenarios.

#### Base WebSocket Server in Python (using `websockets` library):

```python
import asyncio
import websockets

async def server(websocket, path):
    try:
        while True:
            message = await websocket.recv()
            print(f"Received message: {message}")
            response = f"Echo: {message}"
            await websocket.send(response)
            print(f"Sent message: {response}")
    except websockets.exceptions.ConnectionClosed:
        print("Connection with client closed")

start_server = websockets.serve(server, "localhost", 6789)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

**Explanation**: This WebSocket server listens for incoming messages and simply echoes them back to the client. This script represents a basic template on which we can build more complex interactions.

### Step 2: Adding Real-Life Fixtures to Template

To enhance this template, we incorporate different real-life fixtures such as a chat system, a stock ticker stream, or IoT device status updates. We'll go with a stock ticker example.

#### Enhanced WebSocket server with Stock Ticker Simulation

```python
import json
import random
import asyncio
import websockets

async def stock_ticker(websocket, path):
    stock_prices = {"AAPL": 150.50, "GOOGL": 2735.20, "MSFT": 295.30}
    try:
        while True:
            for stock, price in stock_prices.items():
                # simulate price change
                updated_price = price + random.uniform(-1, 1)
                stock_prices[stock] = updated_price
                await websocket.send(json.dumps({stock: updated_price}))
                await asyncio.sleep(1)  # update every second
    except websockets.exceptions.ConnectionClosed:
        print("Connection with client closed")

start_server = websockets.serve(stock_ticker, "localhost", 6789)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

**Explanation**: This WebSocket server simulates a stock ticker by sending updated stock prices in JSON format to the client every second. This simulates real-time data streaming, a common use case for WebSockets in real-life applications.

### Step 3: Utilizing AsyncAPI for Structuring the WebSocket Communication

For documenting and designing our WebSocket communications, we should use AsyncAPI. This specification helps standardize and understand the API’s lifecycle.

#### Sample AsyncAPI Specification:

```yaml
asyncapi: 2.0.0
info:
  title: Stock Ticker WebSocket API
  version: '1.0.0'
  description: This API allows you to receive real-time stock price updates.
servers:
  development:
    url: localhost:6789
    protocol: ws
channels:
  stockTicker:
    subscribe:
      summary: Receive real-time stock price updates
      message:
        contentType: application/json
        payload:
          type: object
          properties:
            AAPL:
              type: number
              format: float
            GOOGL:
              type: number
              format: float
            MSFT:
              type: number
              format: float
```

**Explanation**: This AsyncAPI document details the structure of the messages, the channels used (in this case, `stockTicker`), and the message contents.

### Step 4: Testing and Documentation

Finally, thorough testing should be conducted to ensure the reliability and efficiency of the WebSocket server. Additionally, detailed documentation should be created based on the AsyncAPI specification for developers to understand its usage quickly.

**Final Remark**: Leverage modern tools and libraries for WebSocket communication and ensure your API is well-documented with AsyncAPI to cater to a broad audience of developers effectively.
```
