### ISSUE TITLE
How to describe an array of objects

### ISSUE THREAD

**Issue by BirukovAleksandr48** [asyncapi/generator#143]
My message payload is array of objects. How I can describe it in yaml? What I tried:
```
message:
    payload:
        type: array
        items:
            type: object
            additionalProperties: false
            properties:
                id:
                    type: string
                name:
                    type: string
```

Is it true?
