### ISSUE TITLE
Support server URL variables

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#182]
Currently, the generator doesn't support server URL variables. For instance, when we have a server like this:

```yaml
servers:
  production:
    url: test.mosquitto.org:{port}
    protocol: mqtt
    description: Test broker
    variables:
      port:
        description: Secure connection (TLS) is available through port 8883.
        default: '1883'
        enum:
          - '1883'
          - '8883'
```

The generated code tries to connect to `mqtt://test.mosquitto.org:{port}`. It would be great if it could replace `port` by a generated value, i.e., the default value or a valid one, based on the variable definition.
