### ISSUE TITLE
Header name should default to Authorization when auth type is http

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#201]
**Applies to:** HTML and Markdown templates.

---

Given this security definition:

```yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: The JWT for authorizing against the backend. Needs to be obtained through the authentication route.
```

It's not possible to define the name of the header but the default value "Authorization" should be shown. At least until we fix [this](https://github.com/asyncapi/asyncapi/issues/307). Currently, we got this:

![image](https://user-images.githubusercontent.com/242119/72885595-847c6900-3d08-11ea-9936-a6174286b1f5.png)

Thanks @luca-moser for reporting the bug 🙌
