### ISSUE TITLE
generate docker file for RabbitMQ to use it with AMQP

### ISSUE THREAD

**Issue by rmelian** [asyncapi/generator#21]
generate a docker file to host RabbitMQ to run applications using AMQP.

**Comment by fmvilas** [comment]
Maybe you want to have a look at Docker Compose.

**Comment by rmelian** [comment]
actually thats what I'm doing. sorry for the misleading title :)


```yml
version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.6.2-management
    ports:
      - 5672:5672
      - 15672:15672
```
