### ISSUE TITLE
The schema files separator got broken recently.

### ISSUE THREAD

**Issue by damaru-inc** [asyncapi/generator#213]
If I have a $$schema$$ file, and this in my document:
```
components:
  schemas:
     Account:
        properties:
           name:
              type: string
```
the generator used to create a file called Account. Now it creates one called anonymous-schema-1.
I can force it to do the right thing by adding a $id property, but I don't think we should force users to do that.
