### ISSUE TITLE
Parameter description does not render in resulting output with html template

### ISSUE THREAD

**Issue by maxs** [asyncapi/generator#249]
In the folowing example `description` field won't be rendered in resulting output because it is not taken from the parameter `toy` but the `schema`.  This means, to have `description`  rendered, we would have to put `description` under `schema` block which is not intended behavior.  

```yml
components:
  parameters:
    toy:
      description: Description of the toy
      schema:
        type: string
```
