### ISSUE TITLE
the 'examples' values should be honored when using type integer+oneOf

### ISSUE THREAD

**Issue by nospam2000** [asyncapi/generator#479]
#### Describe the bug
The automatically created examples don't honor the specified values of 'examples' and create invalid combinations of attributes. The result is a logically invalid example.

#### How to Reproduce
definition:
```
    arrayValueRank:
      description: >
        This Attribute indicates whether the val Attribute of the datapoint is an
        array and how many dimensions the array has.
      type: integer
      default: -1
      examples:
        - 2
      oneOf:
        - const: -1
          description: 'Scalar: The value is not an array.'
        - const: 0
          description: 'OneOrMoreDimensions: The value is an array with one or more dimensions.'
        - const: 1
          description: 'OneDimension: The value is an array with one dimension.'
        - const: 2
          description: 'The value is an array with two dimensions.'

    arrayArrayDimensions:
      type: array
      items:
        type: integer
        minimum: 0
      examples:
        - [3, 5]
```

The created invalid example
```
              "valueRank": -1,
              "arrayDimensions": [
                3,
                5
              ],
```

'-1' means a scalar value, but for the example of arrayDimensions valueRank has to be '2'

#### Expected behavior
expected example:
```
              "valueRank": 2,
              "arrayDimensions": [
                3,
                5
              ],
```
use the value '2' as the only value provided in 'examples' for valueRank. Instead the first value of the valueOf is used.

Changing the order of the values in my schema will also confuse the user, because they shall be numerically sorted and the first value makes no sense as example.
