### ISSUE TITLE
Error: This template requires the following missing params: server with @asyncapi/nodejs-template

### ISSUE THREAD

**Issue by DavidBiesack** [asyncapi/generator#579]
#### Describe the bug

Running the generator with the sample yields an error
```
Something went wrong:
Error: This template requires the following missing params: server.
```

#### How to Reproduce
Copy the sample `asyncapi.yaml` from [https://www.asyncapi.com/docs/tutorials/streetlights](https://www.asyncapi.com/docs/tutorials/streetlights)

```yaml
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
channels:
  light/measured:
    publish:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      operationId: onLightMeasured
      message:
        name: LightMeasured
        payload:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: Id of the streetlight.
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              type: string
              format: date-time
              description: Date and time when the message was sent.
```

install the most recent generator (1.6.13) and template

```bash
npm i -g @asyncapi/generator
npm i -g @asyncapi/nodejs-template
```

Try to generate using the nodejs-template:

```bash
ag --output node-sdk asyncapi.yaml @asyncapi/nodejs-template
Something went wrong:
Error: This template requires the following missing params: server.
    at isRequiredParamProvided (~/.nvm/versions/node/v12.21.0/lib/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:57:11)
    at module.exports.validateTemplateConfig (/~/.nvm/versions/node/v12.21.0/lib/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:21:3)
    at Generator.generate (/~/.nvm/versions/node/v12.21.0/lib/node_modules/@asyncapi/generator/lib/generator.js:179:5)
    at ~/.nvm/versions/node/v12.21.0/lib/node_modules/@asyncapi/generator/cli.js:132:9

```

#### Expected behavior

correct code gen
