### ISSUE TITLE
Referencing AsyncAPI specs to reuse messages and schemas generates Java classes with incorrect names

### ISSUE THREAD

**Issue by manoswerts** [asyncapi/generator#614]
#### Describe the bug
When generating Java code from an AsyncAPI spec which references another one for reuse, schemas from the referenced AsyncAPI spec are named `AnonymousSchema<#>.java` instead of using the schema name.

Java classes are generated correctly for schema's in the main AsyncAPI spec.

#### How to Reproduce
Ensure that you have 2 AsyncAPI specs of which one references the other to reuse a message.

asyncapi.yaml
```
channels:
  user.update:
    publish:
      summary: User is updated
      message:
        $ref: '<url-or-path-to-other-asyncapi-yaml>l#/components/messages/user'
```

other-asyncapi.yaml
```
components:
    messages:
        user:
            contentType: 'application/json'
        payload:
            $ref: '#/components/schemas/User'

  schemas:
      User:
          type: object
          properties:
              [...]
```

Execute `ag asyncapi.yaml @asyncapi/java-spring-template`

#### Expected behavior
A Java class is generated for schema `User` called `User.java`.
