### ISSUE TITLE
Reference to local file doesn't work

### ISSUE THREAD

**Issue by marcortw** [asyncapi/generator#65]
I am playing around with references to local files and can't get it to work with the generator and referencing a yaml file.

basic_example_refs.yml:
```yaml
asyncapi: '2.0.0-rc1'
id: 'urn:array.example.com'

info:
  title: Very simple example
  version: '1.0.0'

channels:
  myChannel:
    publish:
      message:
        description: Simple example
        payload:
          $ref: './myObject.yml#/myObject'

components:
  schemas:
    myObject:
      type: object
      properties:
        key1:
          title: A key
          type: string
          default: "foo"
          enum:
            - foo
            - bar
          description: Just an example enum
```
myObject.yml:
```yaml
myObject:
  type: object
  properties:
    key1:
      title: A key
      type: string
      default: "foo"
      enum:
        - foo
        - bar
      description: Just an example enum

```
Both are in the same directory. I am trying this on Windows. When doing this with the myObject.yml file, I get the following error:
```
C:\[...]\asyncapi-test\asyncapi-refs>ag basic_example_refs.yml html
2019/06/12 17:15:38 invalid character 'm' looking for beginning of value
```
After reading [reusing messages](https://www.asyncapi.com/docs/getting-started/reusing-messages/), I thought that yaml files can be used. [The 2.0.0-rc1 spec](https://www.asyncapi.com/docs/specifications/2.0.0-rc1/#referenceObject) and [this issue](https://github.com/asyncapi/asyncapi/issues/216) indicate that it might not be possible, though. However, when I am trying the same thing with a local json file, it works:

Changed basic_example_refs.yml:
```yaml
        payload:
          $ref: './myObject.json#/myObject'
```
myObject.json:
```json
{
  "myObject": {
    "type": "object",
    "properties": {
      "key1": {
        "title": "A key",
        "type": "string",
        "default": "foo",
        "enum": [
          "foo",
          "bar"
        ],
        "description": "Just an example enum"
      }
    }
  }
}

```
```
C:\[...]\asyncapi-test\asyncapi-refs>ag basic_example_refs.yml html
Done! ✨
Check out your shiny new generated files at C:\[...]\asyncapi-test\asyncapi-refs.
```
Is this an issue of the generator or am I doing something wrong here? Thanks in advance,
Marco

**Comment by fsimard** [comment]
I am not sure its mandatory to have this structure. But this is how i make it work.

the reference should point to the type of object you want
`$ref: 'myObject.yml#/components/schemas/myObject'`

and inside the file myObject.yml

```
components:
  schemas:
    myObject:
...
```
