### ISSUE TITLE
HTML generator doesn't output multiple example messages in oneOf

### ISSUE THREAD

**Issue by sirnewton01** [asyncapi/generator#67]
Using this example model if you generate the HTML from it you can only see one example message leaving the others hidden to the reader of the documentation.

```
# Standard header elements

channels:
  /socket/{subscription_id}:
    parameters:
      - name: subscription_id
        schema:
          type: string
    publish:
      message:
        oneOf:
          - summary: Register subscription
            contentType: application/json
            payload:
              type: object
              properties:
                name:
                  type: string
                  enum: [register]
          - summary: Send still alive message to the Hive.
            contentType: application/json
            payload:
              type: object
              properties:
                name:
                  type: string
                  enum: [still_alive]
                payload:
                  type: object
                  properties:
                    id:
                      type: string
                      description: This is the id from the keep_alive message.
```
