### ISSUE TITLE
Cannot set the AMQP exchange when using the @asyncapi/nodejs-template for subscribing to messages

### ISSUE THREAD

**Issue by adrianvolpe** [asyncapi/generator#716]
#### Describe the bug
I created an asyncapi.yaml file for a channel that had both a subscribe and publish with amqp binding.  When I tried to set the exchange to connect to the code refused to use the supplied value.  I found that the NPM module `fmvilas/hermes-amqp` was trying to set the exchange value with the parameter option `exchangeOptions`.    I changed this to be `exchange` to match the documentation and the issue was resolved.  I have made a pull request against the module in question and noticed that it has not been updated in 2 years.  Given it is part of this generator solution I thought I should raise an issue here.

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
- Use the following specification file
  https://gist.github.com/adrianvolpe/27e9f02187c5b31247aaf947fa4a7360

- Use the asyncapi/generator to generate a nodejs template:
   ```
   ag ./demo.yml @asyncapi/nodejs-template -o code -p server=dev
   ```
- Modify the `common.yml` file to have the values:
  ```
  broker:
    amqp:
      exchange: "DEMO"
      subscribe: true
      username:
      password:
      host: 
      port:
      topics: ["DEMO.ASSESSMENT.*"]
      vhost: MSP
      queue: demo.assessment.amqp.api.1.0.0
      queueOptions:
        exclusive: false
        durable: true
        autoDelete: true
  ```

 - Start a local RabbitMQ instance using docker or as a process.
  Docker command:
  ```
   docker run -d -p 5672:5672 -p 15672:15672 rabbitmq:3.9.10-management
  ```

- Run the nodejs template with:
  ```
   #first install the npm modules
   npm i
  
  # then start the app
  npm start
  ```
- Connect to the RabbitMQ console and check the status of the connection
  http://localhost:15672. 

The following screenshot is what happens today with the exchange value being ignored:
![UnexpectedBehaviour](https://user-images.githubusercontent.com/12508724/143504995-7b9f7821-f555-41e1-bc5e-a3d2267c4971.png)

The following is a screenshot of the expected behaviour:
![Expected behaviour](https://user-images.githubusercontent.com/12508724/143505037-f1c1aaab-4b0b-489a-b63d-f45894fb2a70.png)

 The pull request for the fix is located at: https://github.com/fmvilas/hermes-amqp/pull/3

#### Expected behavior
When the `config/common.yml` file has a value for the attribute `broker.amqp.exchange` that value is honoured and used as part of the subscription and not ignored.  See the expected behaviour screenshot above.
