### ISSUE TITLE
HTML Doc: Pattern string is being capitalized

### ISSUE THREAD

**Issue by marcelomorgado** [asyncapi/generator#73]
The `must match XXX` badge from the schema is being capitalized (text-transform: capitalize)
Example:

```
schemas:
    Foo:
      type: object
      properties:
        bar:
          type: string
          pattern: "^hello$"
```

Is being shown as `Must Match ^Hello$`

In somehow it's related to https://github.com/asyncapi/generator/pull/62/files
