### ISSUE TITLE
Cannot get v0.10.0 cli to work

### ISSUE THREAD

**Issue by laat** [asyncapi/generator#90]
```helloworld.yaml```:
```yaml
asyncapi: '2.0.0-rc1'
id: 'urn:hello-world-app'
info:
  title: Hello world application
  version: '0.1.0'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.htm
channels:
  hello:
    subscribe:
      message:
        payload:
          type: string
          pattern: '^hello .+$'
```

With v0.9.0:
```
$ npx asyncapi-generator@0.9.0 --output dist/ helloworld.yaml html
Done! ✨
Check out your shiny new generated files at /Users/laat/git/example/dist.
```

With v0.10.0:
```
$ npx asyncapi-generator@0.10.0 --output dist/ helloworld.yaml html
Something went wrong:
TypeError: Cannot read property 'index.html' of undefined
    at Generator.generateFile (/Users/laat/.npm/_npx/34040/lib/node_modules/asyncapi-generator/lib/generator.js:381:47)
    at Walker.walker.on (/Users/laat/.npm/_npx/34040/lib/node_modules/asyncapi-generator/lib/generator.js:288:26)
    at Walker.emit (events.js:198:13)
    at Object.emitSingleEvents [as emitNodeType] (/Users/laat/.npm/_npx/34040/lib/node_modules/asyncapi-generator/node_modules/walk/lib/node-type-emitter.js:58:13)
    at Walker._wLstatHandler (/Users/laat/.npm/_npx/34040/lib/node_modules/asyncapi-generator/node_modules/walk/lib/walk.js:88:19)
    at /Users/laat/.npm/_npx/34040/lib/node_modules/asyncapi-generator/node_modules/walk/lib/walk.js:106:12
    at FSReqWrap.oncomplete (fs.js:154:5)
```

initial investigation suggests that `.tp-config.json` is missing in the template folder in this repository
