### ISSUE TITLE
Template list workflow runs on every forked repository

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/generator#921]
#### Describe the bug
Everyday github runs a workflow based on [templates-list-validator](https://github.com/asyncapi/generator/blob/master/.github/workflows/templates-list-validation.yml) .
The bug here is that this workflow runs on every forked repository also, which I think is not the aim of this workflow.

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

- Screenshots
![image](https://user-images.githubusercontent.com/81870866/223930051-9d1da9ae-3a18-4dc8-9fa5-5f3ce71da362.png)

This issue can be resolved by adding an if statement which checks for only asyncapi repository.

**Comment by sambhavgupta0705** [comment]
@derberg can you please approve this issue.
Here cron jobs is doing work correctly,just an error here is that  it is running test on every forked repository also

**Comment by sambhavgupta0705** [comment]
```
jobs:
  templates:
    if: startsWith(github.repository, 'asyncapi/')
    name: 'Check list of templates'

```
Proposed solution for this

**Comment by derberg** [comment]
To be honest I think it is about time to probably remove the whole workflow and related custom action and instead, we should just make sure all templates are listed in https://www.asyncapi.com/tools 🤔

**Comment by derberg** [comment]
well we need to create 13 PRs in different repos to add `.asyncapi-tool` file there 😄 

- https://github.com/asyncapi/dotnet-rabbitmq-template
- https://github.com/asyncapi/dotnet-nats-template
- https://github.com/asyncapi/php-template
- https://github.com/asyncapi/java-template
- https://github.com/asyncapi/java-spring-template
- https://github.com/asyncapi/java-spring-cloud-stream-template
- https://github.com/asyncapi/ts-nats-template
- https://github.com/asyncapi/python-paho-template
- https://github.com/asyncapi/go-watermill-template
- https://github.com/asyncapi/nodejs-ws-template
- https://github.com/asyncapi/markdown-template
- https://github.com/asyncapi/nodejs-template
- https://github.com/asyncapi/html-template

example:
```yml
title: .NET RabbitMQ
filters:
    language: 'C#'
    technology:
        - AsyncAPI Generator
        - '.NET'
        - RabbitMQ
    categories:
        - code-generator
    hasCommercial: false
```

I'm only thinking that because there are so many AsyncAPI Generator templates, and more will come, that maybe we need a separate `category` for it. @akshatnema thoughts?
