### ISSUE TITLE
v1.10.0 does not support local files in $ref

### ISSUE THREAD

**Issue by eivindga** [asyncapi/generator#963]
#### Describe the bug
The latest version of the parser does not support '$ref' used anywhere in asyncapi-files, referencing local files when generating doc. 

#### How to Reproduce

Try to include a local file using ref in: 
- message example 
- description field

Example of message: 

```
  'aggregate.vehicle.journey.v2':
    description:
      $ref: markdown/VehicleJourneyV2.md
    subscribe:
      message:
        name: VehicleJourneyV2
        schemaFormat: application/vnd.apache.avro;version=1.9.0
        payload:
          $ref: schema/VehicleJourneyV2
        examples: [
          { $ref: examples/VehicleJourneyV2_deadrun.json },
          { $ref: examples/VehicleJourneyV2_servicejourney.json }
        ]
        bindings:
          kafka:
            compact: false
           
```

#### Expected behavior
Latest version should work in the same way as v1.9.18.
