### ISSUE TITLE
v1.10.6 does not support absolute path in $ref

### ISSUE THREAD

**Issue by dvemnt** [asyncapi/generator#987]
#### Describe the bug
The latest version of the parser does not support referencing by absolute path. It works in previous versions.

#### How to Reproduce
1. Create Async API doc file with absolute path `$ref` and file on this path in same folder.
2. Try to build using HTML template.

```yaml
asyncapi: "2.4.0"
defaultContentType: application/json

info:
  title: Test Absolute Path
  version: "1.0.0"

channels:
  TestOperation:
    publish:
      message:
        $ref: "/absolute-path/File.yaml"
```

#### Expected behavior
Done! ✨
Check out your shiny new generated files at ...

### Actual behavior
```
Something went wrong:
Error: Input is not a corrent AsyncAPI document so it cannot be processed.
    at Generator.generateFromString (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:264:19)
    at async /usr/local/lib/node_modules/@asyncapi/generator/cli.js:157:9
Errors:
[
  {
    "code": "invalid-ref",
    "path": [
      "channels",
      "TestOperation",
      "publish",
      "message",
      "$ref"
    ],
    "message": "ENOENT: no such file or directory, open '/absolute-path/absolute-path/File.yaml'",
    "severity": 0,
    "range": {
      "start": {
        "line": 11,
        "character": 14
      },
      "end": {
        "line": 11,
        "character": 40
      }
    },
    "source": "/absolute-path/asyncapi.yaml"
  }
]

```
